version: '3.7'

services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=database
    ports:
      - 8011:3306
    volumes:
      - ./db_data:/etc/mysql/conf.d

  app:
    image: rgiraon/webserver
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
      - PHP_DEBUGGER="xdebug"
      - XDEBUG_REMOTE_AUTOSTART=On
      - XDEBUG_REMOTE_CONNECT_BACK=Off
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - XDEBUG_REMOTE_PORT=9090
      - XDEBUG_PROFILER_ENABLE=Off
      - PHP_DATE_TIMEZONE=UTC
      - PHP_DISPLAY_ERRORS=0
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    links:
      - db
    depends_on:
      - db
    tty: true